version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  terraform: circleci/terraform@3.0.1

defaults: &defaults
    docker:
      - image: cimg/node:17.4.0
    working_directory: ~/project
    environment:
      TF_IN_AUTOMATION: true


yarn-install: &yarn-install
  run:
    name: yarn-install
    command: |
      curl -o- -L https://yarnpkg.com/install.sh | bash

jobs:
  plan-apply:
    <<: *defaults
    # requires terraform backend to be created for ci
    # ideally, S3 backend would be created for each build (to allow simultaneous builds), but I blocked on this 
    # https://github.com/circleci/circleci-docs/issues/6355
    steps:
      - checkout
      - aws-cli/install
      - terraform/install
      - *yarn-install
      - run:
          name: terraform init & plan
          command: |
            STAGE="ci" yarn run tf:service:init -reconfigure -input=false
            STAGE="ci" yarn run tf:service:plan -out plan.tfplan
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  apply:
    <<: *defaults
    steps:
      - aws-cli/install
      - terraform/install
      - *yarn-install
      - attach_workspace:
          at: ~/project
      - run:
          name: terraform
          command: |
            STAGE="ci" yarn run tf:terraform apply -auto-approve plan.tfplan
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  plan-destroy:
    <<: *defaults
    steps:
      - aws-cli/install
      - terraform/install
      - *yarn-install
      - attach_workspace:
          at: ~/project
      - run:
          name: terraform create destroy plan
          command: |
            STAGE="ci" yarn run tf:service:plan -destroy -out plan.tfdestroy
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  destroy:
    <<: *defaults
    steps:
      - aws-cli/install
      - terraform/install
      - *yarn-install
      - attach_workspace:
          at: ~/project
      - run:
          name: terraform destroy
          command: |
            STAGE="ci" yarn run tf:terraform apply -auto-approve plan.tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - apply:
          requires:
            - plan-apply
      - plan-destroy:
          requires:
            - apply
      - destroy:
          requires:
            - plan-destroy
